batch_size: 4
path: config\path.yaml
weight_path: weight/Dheap_weight.pt
lr: 0.001
epoch: 50
optimizer: SGD
schedual: StepLR
momentum: 0.9
size_img: [320,480]
class_dict: config\class_dict.yaml
length: 30
angle: [0.784,1.57,2.355]
long_class: [20,40]
T: 0.5
epsilon: 0.9
SOA: 0.5